-- Prant logins are now in Supabase (Authentication + public.user_roles).
-- No local users table; this file is unused.
-- To add director/prant users, create them in Supabase Auth and run the
-- user_roles seed in Supabase SQL Editor (see seed-supabase-user-roles*.sql in this folder).
